title: jekyllDev
email: xqzhang77030@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A paragraph describing your webpage.
baseurl: "/blog" # the subpath of your site
url: "assisi.care" # the base hostname & protocol for your site
github_username: Xinqiao77

# Required plugins for the theme to work properly
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md


# controls how big the shell and font looks
font-size: small # options: [small] or [large]

